### ISSUE TITLE
Does not seem to work with macOS DP2 or Public Beta

### ISSUE THREAD

**Issue by hunty1** [VMwareFusion/sierra-vm-installer-fix#5]
Host: iMac Late 2012 also tried with MacBookPro 15" Mid 2015
Host OS: 10.11.5 15F34 and 10.10.5 14F27
VMWare Fusion version: 8.1.1 (build 3771013)

Replaced the Create Mavericks tool, ensured owner and mode permissions correct.
Rebooted host machine

Still get the following error: Unable to Create Install Media

![screen shot 2016-07-13 at 11 40 13 am](https://cloud.githubusercontent.com/assets/7887711/16789226/102c8b04-48ef-11e6-8f76-478312443ed8.png)

**Comment by gcox** [comment]
That error should be resolved by rebooting your Mac.

**Comment by simplepanda** [comment]
Reboot doesn't solve the issue. Same OS / VMware versions as the OP above (Mac Pro 2013 for me though).

Back trace:

```
2016-07-13T19:14:29.040-05:00| VMware Fusion| I125: Cmd /host2/#_client/util/file/cmd/##e/op/stat/ failed: Invalid path
2016-07-13T19:14:29.044-05:00| VMware Fusion| I125: Current OS Release is 15.5.0
2016-07-13T19:14:29.045-05:00| VMware Fusion| I125: __116-[DUIDeviceHardDisk applyChangesForTransaction:newSize:resizePartition:newFilePath:dlgMgr:abortHandler:doneHandler:]_block_invoke File /Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk exists: Y
2016-07-13T19:14:29.289-05:00| vthread-7| I125: VTHREAD initialize thread 7 "vthread-7" tid 20793952
2016-07-13T19:14:29.289-05:00| vthread-7| W115: FILE: FileLockCreateEntryDirectory creation failure on '/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk.lck': Permission denied
2016-07-13T19:14:29.289-05:00| vthread-7| W115: FILE: FileLockIntrinsicPortable implicit S lock succeeded on '/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk'.
2016-07-13T19:14:29.290-05:00| vthread-7| W115: FILE: FileLockCreateEntryDirectory creation failure on '/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk.lck': Permission denied
2016-07-13T19:14:29.290-05:00| vthread-7| W115: FILE: FileLockIntrinsicPortable implicit S lock succeeded on '/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk'.
2016-07-13T19:14:29.290-05:00| vthread-7| I125: DISKLIB-DSCPTR: Opened [0]: "preformattedHFSVolume.vmdk" (0xe)
2016-07-13T19:14:29.290-05:00| vthread-7| I125: DISKLIB-LINK  : Opened '/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk' (0xe): monolithicSparse, 83886080 sectors / 40 GB.
2016-07-13T19:14:29.290-05:00| vthread-7| I125: DISKLIB-LIB   : Opened "/Applications/VMware Fusion.app/Contents/Resources/preformattedHFSVolume.vmdk" (flags 0xe, type monolithicSparse).
2016-07-13T19:14:29.291-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CREATE: "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Virtual Disk.vmdk" -- monolithicSparse capacity=0 (0 bytes) adapter=Invalid info=grainSize=128 objType= policy=''
2016-07-13T19:14:29.291-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CREATE: "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Virtual Disk.vmdk" -- monolithicSparse capacity=83886080 (40 GB) adapter=lsilogic info=grainSize=128 objType=file policy=''
2016-07-13T19:14:29.291-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CREATE: Creating disk backed by 'default'
2016-07-13T19:14:29.293-05:00| vthread-7| I125: DISKLIB-DSCPTR: "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Virtual Disk.vmdk" : creation successful.
2016-07-13T19:14:29.323-05:00| vthread-7| I125: DISKLIB-DSCPTR: Opened [0]: "Virtual Disk.vmdk" (0x218)
2016-07-13T19:14:29.323-05:00| vthread-7| I125: DISKLIB-LINK  : Opened '/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Virtual Disk.vmdk' (0x218): monolithicSparse, 83886080 sectors / 40 GB.
2016-07-13T19:14:29.323-05:00| vthread-7| I125: DISKLIB-LIB   : Opened "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Virtual Disk.vmdk" (flags 0x218, type monolithicSparse).
2016-07-13T19:14:29.323-05:00| vthread-7| I125: DDB: "virtualHWVersion" = "6" (was "12")
2016-07-13T19:14:29.326-05:00| vthread-7| I125: DDB: "longContentID" = "56a8249cd63b5f7707009d09713044c2" (was "a32c006e5a077fa37b496fa3fffffffe")
2016-07-13T19:14:29.806-05:00| vthread-7| I125: VTHREAD initialize thread 7 "vthread-7" tid 20794024
2016-07-13T19:14:29.807-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CREATE: "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Temporary Installation Source Disk.vmdk" -- monolithicSparse capacity=2048 (1 MB) adapter=lsilogic info=grainSize=128 objType= policy=''
2016-07-13T19:14:29.807-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CreateObjExtParams: Object backing type 0 is invalid. Figuring out the most suitable backing type...
2016-07-13T19:14:29.807-05:00| vthread-7| I125: DISKLIB-LIB_CREATE   : CREATE: Creating disk backed by 'default'
2016-07-13T19:14:29.807-05:00| vthread-7| I125: DISKLIB-DSCPTR: "/Volumes/VM and Backup/Virtual Machines.localized/OS X 10.12 Sierra Public Beta.vmwarevm/Temporary Installation Source Disk.vmdk" : creation successful.
```

**Comment by hunty1** [comment]
Yep tried multiple reboots - no deal

**Comment by sadcup** [comment]
Please try to delete the chmod line and see if that works.

```
chmod u+r "$outputMnt"/.Trashes
```

**Comment by hunty1** [comment]
commenting out the  chmod u+r line as mentioned above now stops the error message, however it results in this message being shown and not finishing. It's been like this for 10 minutes, with no disk activity shown in activity monitor...

![screen shot 2016-07-14 at 12 03 44 pm](https://cloud.githubusercontent.com/assets/7887711/16825813/3cefe25e-49bb-11e6-9ad0-48b9f41c9f06.png)

For what its worth

This script from Rich works great with the DP2 and PB and creates a DMG that can be used to install sierra 

https://github.com/rtrouton/create_os_x_vm_install_dmg

**Comment by vMikero** [comment]
We've updated the script and it seems to be working... Can you guys test?
In macOS 10.12 beta 2, the Finder will not create a .Trashes directory
automatically, so we have to wrap an if statement around the chmod operation

**Comment by hunty1** [comment]
Still not working for me ¯\_(ツ)_/¯ 

ended up using Rich's script that I linked above and it works fine.

**Comment by hunty1** [comment]
Yeah still doesn't work but whatever......
